gateways:
  # athena:
  #   connection:
  #     type: athena
  #     work_group: primary
  #     region_name: eu-central-1
  #     s3_staging_dir: s3://sumeo-parquet-data-lake/athena/ 
  #     s3_warehouse_location: s3://sumeo-parquet-data-lake/multiengine/metrics/
  duckdb_local:
    connection:
      type: duckdb
      catalogs:
        persistent: 'local.duckdb'
        ephemeral: ':memory:'
  duckdb_pg:
    connection:
      type: duckdb
      catalogs:
        main_db:
          type: postgres
          path: 'dbname=main_db user=postgres password=password host=127.0.0.1'
      extensions:
        - name: iceberg
  postgres:
    connection:
      type: postgres
      database: main_db
      user: postgres
      password: password
      host: 127.0.0.1
      port: 5432

default_gateway: postgres

model_defaults:
  start: 2025-02-28 20:00:00
  dialect: duckdb